[build]
  publish = "."

[processing]
  skip_processing = false

[processing.html]
  pretty_urls = true

[[redirects]]
  from = "/admin"
  to = "/admin/login"
  status = 301
  force = true

[[redirects]]
  from = "/admin/"
  to = "/admin/login"
  status = 301
  force = true

[[redirects]]
  from = "/index.html"
  to = ""
  status = 301
  force = true

[[redirects]]
  from = "/404.html"
  to = "/404"
  status = 301
  force = true

